### ISSUE TITLE
thread 'main' panicked at 'attempt to subtract with overflow', src/main.rs:76:15

### ISSUE THREAD

**Issue by tbaumann** [willdoescode/nat#5]
My Ubuntu rust packages are probably quite old. But I don't think it matters too much.

```
tilmanb@zuse:~/git/nat$ RUST_BACKTRACE=1 cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.07s
     Running `target/debug/nat`
thread 'main' panicked at 'attempt to subtract with overflow', src/main.rs:76:15
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /usr/src/rustc-1.43.0/vendor/backtrace/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /usr/src/rustc-1.43.0/vendor/backtrace/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1063
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1426
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:204
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:224
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:470
  11: rust_begin_unwind
             at src/libstd/panicking.rs:378
  12: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
  13: core::panicking::panic
             at src/libcore/panicking.rs:52
  14: nat::main
             at src/main.rs:76
  15: std::rt::lang_start::{{closure}}
             at /usr/src/rustc-1.43.0/src/libstd/rt.rs:67
  16: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:52
  17: std::panicking::try::do_call
             at src/libstd/panicking.rs:303
  18: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:86
  19: std::panicking::try
             at src/libstd/panicking.rs:281
  20: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  21: std::rt::lang_start_internal
             at src/libstd/rt.rs:51
  22: std::rt::lang_start
             at /usr/src/rustc-1.43.0/src/libstd/rt.rs:67
  23: main
  24: __libc_start_main
  25: _start
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
permissions   size      last modified       grouptilmanb@zuse:~/git/nat$
```
```
tilmanb@zuse:~/git/nat$ git log -n 1
commit 6d34b3c80b77f94e2f076158affcb8e6ba8d9b04 (HEAD -> main, origin/main, origin/HEAD)
Author: Will Lane <williamlane923@gmail.com>
Date:   Fri Oct 23 00:29:00 2020 -0700

    updated colors for users using lighter terminal themes
```

```
tilmanb@zuse:~/git/nat$ rustc --version
rustc 1.43.0
```

My rust foo is very weak and I didn't have tome to dig into it. But perhaps you want to know.

Feel free to just close the ticket.

**Comment by Nikolasel** [comment]
Having a group length smaller than 8 causes this integer underflow in the following line.

https://github.com/willdoescode/nat/blob/6d34b3c80b77f94e2f076158affcb8e6ba8d9b04/src/main.rs#L76

It crashes the software in debug mode and causes many underlined prints in release mode.

**Comment by willdoescode** [comment]
I am adding a fix to this right now

**Comment by willdoescode** [comment]
should be fixed now. let me know if you have any issue with the latest release.

**Comment by a0n** [comment]
on the most recent commit in main i get the following output:

```
➜ cargo build && cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.04s
    Finished dev [unoptimized + debuginfo] target(s) in 0.02s
     Running `target/debug/nat`
thread 'main' panicked at 'attempt to subtract with overflow', src/main.rs:58:25
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
permissions   size      last modified       group% 
```

**Comment by willdoescode** [comment]
this should be fixed in the latest release
