### ISSUE TITLE
Error when running nat on unaccessible directory

### ISSUE THREAD

**Issue by Devnol** [willdoescode/nat#71]
When running nat on a directory the user does not have access to, a rust error occurs instead of a soft app error such as a simple "permission denied". For example:
```
~ natls /path/that/I/dont/have/access/to
thread 'main' panicked at 'Failed to run natls: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }', src/main.rs:443:8
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

I would expect it to throw a soft and less "intimidating" error such as:
```
~ ls /path/that/I/dont/have/access/to
ls: /path/that/I/dont/have/access/to: Permission denied
```

**Comment by willdoescode** [comment]
Do you mind running `RUST_BACKTRACE=1 natls /path/that/I/dont/have/access/to` so that I can see the backtrace?

**Comment by Devnol** [comment]
certainly. Here it is:
```
thread 'main' panicked at 'Failed to run natls: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }', src/main.rs:443:8
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::result::unwrap_failed
   3: natls::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

Here's the full backtrace in case you need that too:
```
thread 'main' panicked at 'Failed to run natls: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }', src/main.rs:443:8
stack backtrace:
   0:        0x10f7e2b2e - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h9e40ebcba40447f1
   1:        0x10f811a4e - core::fmt::write::h6b7da6f017cb0981
   2:        0x10f7de10a - std::io::Write::write_fmt::h0d7586a804f8fb0a
   3:        0x10f7f8869 - std::panicking::default_hook::{{closure}}::h3008855a88939ece
   4:        0x10f7f842f - std::panicking::default_hook::h56f0053f999d1c13
   5:        0x10f7f8dfa - std::panicking::rust_panic_with_hook::ha22e523c214d3b3f
   6:        0x10f7e3035 - std::panicking::begin_panic_handler::{{closure}}::h49e36beb793978ea
   7:        0x10f7e2c78 - std::sys_common::backtrace::__rust_end_short_backtrace::h2449b20751cd426e
   8:        0x10f7f8973 - _rust_begin_unwind
   9:        0x10f817ddf - core::panicking::panic_fmt::h51737faccadfdf20
  10:        0x10f817ce5 - core::result::unwrap_failed::he9061337264f66ab
  11:        0x10f771e97 - natls::main::h3212f6c42b1095a8
  12:        0x10f77253a - std::sys_common::backtrace::__rust_begin_short_backtrace::h2c5f1ab999debe7e
  13:        0x10f772a0c - std::rt::lang_start::{{closure}}::hb46e8c0fcf84abaa
  14:        0x10f7fc320 - std::rt::lang_start_internal::h1ddd54569c9d0ff5
  15:        0x10f772509 - _main
  ```

**Comment by willdoescode** [comment]
yeah I was just interested in the line number.

**Comment by Devnol** [comment]
the line was in the initial message too (if you mean main.rs:443:8)

**Comment by willdoescode** [comment]
which directory did you run the command on, im having a hard time finding files I dont have access to.

**Comment by Devnol** [comment]
lmao, try /usr/local/Frameworks or any other user's folder such as Documents

**Comment by willdoescode** [comment]
/usr/local/Frameworks works for me, im on the hunt for files that I dont have access to now

**Comment by Devnol** [comment]
yeah it works for me too apparently. Just try a different user's files if you have that. Or simply run `sudo touch file && sudo chmod 700 file`

**Comment by willdoescode** [comment]
![Screen Shot 2021-03-10 at 13 17 39](https://user-images.githubusercontent.com/53620720/110698835-fe88df00-81a2-11eb-921a-8d1cd19895aa.png)
I got the errors working now!

**Comment by Devnol** [comment]
epic!

**Comment by willdoescode** [comment]
I will push a new build in a moment.

**Comment by willdoescode** [comment]
new cargo build is pushed I will push a new release in a moment as well.

**Comment by willdoescode** [comment]
Issue should be resolved.

**Comment by Devnol** [comment]
Can confirm, it has been resolved!

**Comment by willdoescode** [comment]
thats good!
